// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.18.0
// source: Replica/Replica.proto

package Replica

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GetStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId int32 `protobuf:"varint,1,opt,name=serverId,proto3" json:"serverId,omitempty"`
}

func (x *GetStatus) Reset() {
	*x = GetStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Replica_Replica_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatus) ProtoMessage() {}

func (x *GetStatus) ProtoReflect() protoreflect.Message {
	mi := &file_Replica_Replica_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatus.ProtoReflect.Descriptor instead.
func (*GetStatus) Descriptor() ([]byte, []int) {
	return file_Replica_Replica_proto_rawDescGZIP(), []int{0}
}

func (x *GetStatus) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

type LeaderStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Alive    bool  `protobuf:"varint,1,opt,name=alive,proto3" json:"alive,omitempty"`
	ServerId int32 `protobuf:"varint,2,opt,name=serverId,proto3" json:"serverId,omitempty"`
}

func (x *LeaderStatus) Reset() {
	*x = LeaderStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Replica_Replica_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaderStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderStatus) ProtoMessage() {}

func (x *LeaderStatus) ProtoReflect() protoreflect.Message {
	mi := &file_Replica_Replica_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderStatus.ProtoReflect.Descriptor instead.
func (*LeaderStatus) Descriptor() ([]byte, []int) {
	return file_Replica_Replica_proto_rawDescGZIP(), []int{1}
}

func (x *LeaderStatus) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

func (x *LeaderStatus) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

type WantToLeadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId int32 `protobuf:"varint,1,opt,name=serverId,proto3" json:"serverId,omitempty"`
}

func (x *WantToLeadRequest) Reset() {
	*x = WantToLeadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Replica_Replica_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WantToLeadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WantToLeadRequest) ProtoMessage() {}

func (x *WantToLeadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Replica_Replica_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WantToLeadRequest.ProtoReflect.Descriptor instead.
func (*WantToLeadRequest) Descriptor() ([]byte, []int) {
	return file_Replica_Replica_proto_rawDescGZIP(), []int{2}
}

func (x *WantToLeadRequest) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

var File_Replica_Replica_proto protoreflect.FileDescriptor

var file_Replica_Replica_proto_rawDesc = []byte{
	0x0a, 0x15, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x2f, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63,
	0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61,
	0x22, 0x27, 0x0a, 0x09, 0x67, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a,
	0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x22, 0x40, 0x0a, 0x0c, 0x6c, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6c, 0x69,
	0x76, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x61, 0x6c, 0x69, 0x76, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x22, 0x2f, 0x0a, 0x11, 0x77,
	0x61, 0x6e, 0x74, 0x54, 0x6f, 0x4c, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x32, 0x93, 0x01, 0x0a,
	0x0e, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x3e, 0x0a, 0x11, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x2e, 0x67,
	0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x1a, 0x15, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x2e, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x41, 0x0a, 0x0f, 0x43, 0x68, 0x6f, 0x6f, 0x73, 0x65, 0x4e, 0x65, 0x77, 0x4c, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x12, 0x1a, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x2e, 0x77, 0x61, 0x6e,
	0x74, 0x54, 0x6f, 0x4c, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12,
	0x2e, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x2e, 0x67, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Replica_Replica_proto_rawDescOnce sync.Once
	file_Replica_Replica_proto_rawDescData = file_Replica_Replica_proto_rawDesc
)

func file_Replica_Replica_proto_rawDescGZIP() []byte {
	file_Replica_Replica_proto_rawDescOnce.Do(func() {
		file_Replica_Replica_proto_rawDescData = protoimpl.X.CompressGZIP(file_Replica_Replica_proto_rawDescData)
	})
	return file_Replica_Replica_proto_rawDescData
}

var file_Replica_Replica_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_Replica_Replica_proto_goTypes = []interface{}{
	(*GetStatus)(nil),         // 0: Replica.getStatus
	(*LeaderStatus)(nil),      // 1: Replica.leaderStatus
	(*WantToLeadRequest)(nil), // 2: Replica.wantToLeadRequest
}
var file_Replica_Replica_proto_depIdxs = []int32{
	0, // 0: Replica.ReplicaService.CheckLeaderStatus:input_type -> Replica.getStatus
	2, // 1: Replica.ReplicaService.ChooseNewLeader:input_type -> Replica.wantToLeadRequest
	1, // 2: Replica.ReplicaService.CheckLeaderStatus:output_type -> Replica.leaderStatus
	0, // 3: Replica.ReplicaService.ChooseNewLeader:output_type -> Replica.getStatus
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Replica_Replica_proto_init() }
func file_Replica_Replica_proto_init() {
	if File_Replica_Replica_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Replica_Replica_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Replica_Replica_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaderStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Replica_Replica_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WantToLeadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Replica_Replica_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Replica_Replica_proto_goTypes,
		DependencyIndexes: file_Replica_Replica_proto_depIdxs,
		MessageInfos:      file_Replica_Replica_proto_msgTypes,
	}.Build()
	File_Replica_Replica_proto = out.File
	file_Replica_Replica_proto_rawDesc = nil
	file_Replica_Replica_proto_goTypes = nil
	file_Replica_Replica_proto_depIdxs = nil
}
